name = "ai-chat-app"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CONVERSATIONS"
class_name = "Conversation"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Conversation"]

[assets]
directory = "public"
